---
- name: Install Docker and Configure Wi-Fi & Access Point
  hosts: my_hosts
  become: yes
  remote_user: ww
  gather_facts: yes
  any_errors_fatal: true

  vars:
    repository_url: 'git@github.com:eshkrab/ww_system.git'
    repository_dest: '/home/ww/ww_system'
    docker_compose_service: 'docker-compose-app'
    avahi_hostname: 'ww_system'

  tasks:
    # Load Wi-Fi credentials from the file
    - name: Include Wi-Fi credentials
      include_vars:
        file: wifi-credentials.conf
        name: wifi

    # Upgrade packages
    - name: Upgrade packages
      apt:
        upgrade: yes
        update_cache: yes

    # Update apt cache
    - name: Update apt cache
      apt:
        update_cache: yes

    # Wi-Fi and Access Point Setup
    - name: Install required packages for Wi-Fi and Access Point
      apt:
        name:
          - vim
          - network-manager
          - hostapd
          - dnsmasq
        state: present
      tags: wifi_access_point

    - name: Configure NetworkManager
      template:
        src: networkmanager.conf.j2
        dest: /etc/NetworkManager/NetworkManager.conf
        owner: root
        group: root
        mode: 0644
      notify: Restart NetworkManager
      tags: wifi_access_point

    - name: Configure hostapd
      template:
        src: hostapd.conf.j2
        dest: /etc/hostapd/hostapd.conf
        owner: root
        group: root
        mode: 0600
      notify: Restart hostapd
      tags: wifi_access_point

    - name: Configure dnsmasq
      template:
        src: dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf
        owner: root
        group: root
        mode: 0644
      notify: Restart dnsmasq
      tags: wifi_access_point

  handlers:
    - name: Restart NetworkManager
      systemd:
        name: NetworkManager
        state: restarted
      listen: Restart NetworkManager

    - name: Restart hostapd
      systemd:
        name: hostapd
        state: restarted

    - name: Restart dnsmasq
      systemd:
        name: dnsmasq
        state: restarted
      listen: Restart dnsmasq

