# ################################ host mode
version: '3'
services:
  gui:
    build: ./gui
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5

  server:
    build: ./server
    network_mode: "host"
    volumes:
      - ./ww_content:/app/content:Z
      - ./config:/app/config:Z
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5

  player:
    build: ./player
    network_mode: "host"
    privileged: true
    volumes:
      - ./ww_content:/app/content
      - ./config:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555"]
      interval: 30s
      timeout: 10s
      retries: 5

  serial:
    build: ./serial
    network_mode: "host"
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # Replace with the actual serial port device
    volumes:
      - ./ww_content:/app/content
      - ./config:/app/config
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5557"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

  # ola:
  #   build: ./ola
  #   network_mode: "host"
  #   privileged: true
  #   volumes:
  #     - ./config:/app/config


# ################################ internal network
# version: '3'
# services:
#   gui:
#     build: ./gui
#     # network_mode: "host"
#     networks:
#       - wwnetwork
#     ports:
#       - 80:80
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:8080"]
#       interval: 30s
#       timeout: 10s
#       retries: 5
#
#   server:
#     build: ./server
#     # network_mode: "host"
#     networks:
#       - wwnetwork
#     ports:
#     #   # - 5555:5555
#       - 8000:8000
#     volumes:
#       - ./ww_content:/app/content:Z
#       - ./config:/app/config:Z
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:8000"]
#       interval: 30s
#       timeout: 10s
#       retries: 5
#
#   player:
#     build: ./player
#     # network_mode: "host"
#     networks:
#       - wwnetwork
#     ports:
#       - 5568:5568/udp
#     privileged: true
#     volumes:
#       - ./ww_content:/app/content
#       - ./config:/app/config
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:5555"]
#       interval: 30s
#       timeout: 10s
#       retries: 5
#
#   ola:
#     build: ./ola
#     networks:
#       - wwnetwork
#     privileged: true
#     volumes:
#       # - ./avahi-daemon.conf:/etc/avahi/avahi-daemon.conf
#       # - ./supervisord.conf:/etc/supervisor/supervisord.conf
#       - ./config:/app/config
#     ports:
#       - 9090:9090
#       - 9010:9010
#
# networks:
#   wwnetwork:
#     driver: bridge
#     driver_opts:
#       com.docker.network.bridge.enable_ip_masquerade: "true"
#     ipam:
#      config:
#        - subnet: 172.20.0.0/16
#          gateway: 172.20.0.1
