---
- name: Configure Wi-Fi & Access Point
  hosts: my_hosts
  become: yes
  remote_user: ww
  gather_facts: yes
  any_errors_fatal: true


  tasks:
    # Load Wi-Fi credentials from the file
    - name: Include Wi-Fi credentials
      include_vars:
        file: ../wifi-credentials.conf
        name: wifi

    # Update apt cache
    - name: Update apt cache
      apt:
        update_cache: yes

    # Wi-Fi and Access Point Setup
    # Install required packages for Wi-Fi and Access Point
    - name: Install required packages for Wi-Fi and Access Point
      apt:
        name:
          - vim
          - network-manager
          - hostapd
          - dnsmasq
        state: present
      tags: wifi_access_point

    # Configure NetworkManager
    - name: Configure NetworkManager
      template:
        src: networkmanager.conf.j2
        dest: /etc/NetworkManager/NetworkManager.conf
        owner: root
        group: root
        mode: 0644
      notify: Restart NetworkManager
      tags: wifi_access_point

    # Configure NetworkManager to ignore wlan0
    - name: Configure NetworkManager to ignore wlan0
      copy:
        content: |
          [main]
          plugins=keyfile

          [keyfile]
          unmanaged-devices=interface-name:wlan0
        dest: /etc/NetworkManager/conf.d/unmanaged.conf
      notify: Restart NetworkManager
      tags: wifi_access_point
      
    - name: Configure Static IP on WLAN0
      template:
        src: wlan0.j2
        dest: /etc/network/interfaces.d/wlan0
        owner: root
        group: root
        mode: 0644
      notify: Restart networking
      tags: wifi_access_point

    # Configure hostapd
    - name: Configure hostapd
      template:
        src: hostapd.conf.j2
        dest: /etc/hostapd/hostapd.conf
        owner: root
        group: root
        mode: 0644
      notify: Restart hostapd
      tags: wifi_access_point

    # Configure dnsmasq
    - name: Configure dnsmasq
      template:
        src: dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf
        owner: root
        group: root
        mode: 0644
      notify: Restart dnsmasq
      tags: wifi_access_point

    # Ensure that the hostapd service is unmasked and enabled
    - name: Unmask hostapd service
      systemd:
        name: hostapd
        masked: no

    - name: Enable hostapd service
      systemd:
        name: hostapd
        enabled: yes

    # Ensure that the dnsmasq service is enabled
    - name: Enable dnsmasq service
      systemd:
        name: dnsmasq
        enabled: yes

  handlers:
    - name: Restart NetworkManager
      service:
        name: NetworkManager
        state: restarted
      listen: Restart NetworkManager

    - name: Restart hostapd
      systemd:
        name: hostapd
        state: restarted

    - name: Restart dnsmasq
      systemd:
        name: dnsmasq
        state: restarted
      listen: Restart dnsmasq

